# Generated by Django 3.0.7 on 2021-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210326_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='class_name',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
